USE Shivamgiri;

CREATE TABLE IF NOT EXISTS AgentProcess (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    EmpCode VARCHAR(100) NOT NULL,
    Name VARCHAR(255) NULL,
    `Process` VARCHAR(255) NULL,
    LOBName VARCHAR(255) NULL,
    Status VARCHAR(100) NULL,
    PRIMARY KEY (ID),
    INDEX IX_AgentProcess_EmpCode (EmpCode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
